services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/event_db
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data:
